-- MySQL Script generated by MySQL Workbench
-- Wed Nov 10 22:55:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar` (
  `idavatar` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `urlImagem` VARCHAR(45) NULL,
  PRIMARY KEY (`idavatar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `dataNascimento` DATETIME NULL,
  `cep` VARCHAR(45) NULL,
  `Pais_idPais` INT NOT NULL,
  `Avatar_idAvatar` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `idPais_idx` (`Pais_idPais` ASC) VISIBLE,
  INDEX `Avatar_idAvatar_idx` (`Avatar_idAvatar` ASC) VISIBLE,
  CONSTRAINT `idPais`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Avatar_idAvatar`
    FOREIGN KEY (`Avatar_idAvatar`)
    REFERENCES `mydb`.`avatar` (`idavatar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `idPlaylist` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `dataCriacao` DATETIME NULL,
  `privado` SMALLINT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPlaylist`),
  INDEX `Usuario_idUsuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `Usuario_idUsuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `idvideo` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  `titulo` VARCHAR(100) NULL,
  `descricao` TEXT NULL,
  `tamanho` DOUBLE NULL,
  `nomeArquivo` VARCHAR(100) NULL,
  `duracao` DOUBLE NULL,
  `imagem` VARCHAR(100) NULL,
  `qtdeReproducoes` INT NULL,
  `qtdeLikes` INT NULL,
  `qtdeDislikes` INT NULL,
  `privado` SMALLINT NULL,
  `dataPublicacao` DATETIME NULL,
  PRIMARY KEY (`idvideo`),
  INDEX `Usuario_idUsuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `Usuario_idUsuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist_video` (
  `Video_idVideo` INT NOT NULL,
  `Playlist_idPlaylist` INT NOT NULL,
  INDEX `Playlist_idPlaylist_idx` (`Playlist_idPlaylist` ASC) VISIBLE,
  INDEX `Video_idVideo_idx` (`Video_idVideo` ASC) VISIBLE,
  CONSTRAINT `Playlist_idPlaylist`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `mydb`.`playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Video_idVideo`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `mydb`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canal` (
  `idCanal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `dataCriacao` DATETIME NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCanal`),
  INDEX `Usuario_idUsuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `Usuario_idUsuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
